//Only need the size to be 1 for latest, but may want to increase this for logging purposes
//Makefile needs to point to this for FSM entries

//Motor CAN Receive

CAN_RECV_ENTRY(MOTOR_IDENTITY, 1, true)
CAN_RECV_ENTRY(MOTOR_ERROR_STATUS, 1, true)
CAN_RECV_ENTRY(BUS_STATUS, 1, true)
CAN_RECV_ENTRY(MOTOR_VELOCITY, 1, true)
CAN_RECV_ENTRY(MOTOR_PHASE_CURRENT, 1, true)
CAN_RECV_ENTRY(MOTOR_VOLTAGE_VECTOR, 1, true)
CAN_RECV_ENTRY(MOTOR_CURRENT_VECTOR, 1, true)
CAN_RECV_ENTRY(MOTOR_BACK_EMF, 1, true)
CAN_RECV_ENTRY(RAIL_15V_STATUS, 1, true)
CAN_RECV_ENTRY(RAIL_3V3_1V9_STATUS, 1, true)
CAN_RECV_ENTRY(HEATSINK_MOTOR_TEMP, 1, true)
CAN_RECV_ENTRY(DSP_BOARD_TEMP, 1, true)
CAN_RECV_ENTRY(ODOMETER_BUS_AH, 1, true)
CAN_RECV_ENTRY(SLIP_SPEED, 1, true)
