/* ======================================================
   AUTO-GENERATED FILE - DO NOT EDIT
   Classic CAN enforced (<=8 bytes)
   ====================================================== */

/**
 * @file filtered.h
 *
 * @brief This header file was generated by cantools version 41.1.1 Thu Feb 26 04:15:48 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef FILTERED_H
#define FILTERED_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define FILTERED_VCU_STATUS_FRAME_ID (0x10u)
#define FILTERED_BPS_STATUS_FRAME_ID (0x01u)
#define FILTERED_DRIVER_INPUT_STATUS_FRAME_ID (0x60u)
#define FILTERED_BRAKE_PRESSURE_FRAME_ID (0x650u)
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_FRAME_ID (0x51u)
#define FILTERED_ACCEL_BRAKE_POSITION_FRAME_ID (0x50u)

/* Frame lengths in bytes. */
#define FILTERED_VCU_STATUS_LENGTH (3u)
#define FILTERED_BPS_STATUS_LENGTH (7u)
#define FILTERED_DRIVER_INPUT_STATUS_LENGTH (6u)
#define FILTERED_BRAKE_PRESSURE_LENGTH (8u)
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_LENGTH (8u)
#define FILTERED_ACCEL_BRAKE_POSITION_LENGTH (5u)

/* Extended or standard frame types. */
#define FILTERED_VCU_STATUS_IS_EXTENDED (0)
#define FILTERED_BPS_STATUS_IS_EXTENDED (0)
#define FILTERED_DRIVER_INPUT_STATUS_IS_EXTENDED (0)
#define FILTERED_BRAKE_PRESSURE_IS_EXTENDED (0)
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_IS_EXTENDED (0)
#define FILTERED_ACCEL_BRAKE_POSITION_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define FILTERED_VCU_STATUS_VCU_FAULT_NO__FAULT_CHOICE (0u)
#define FILTERED_VCU_STATUS_VCU_FAULT_MOTOR__CONTACTOR__SENSE_CHOICE (1u)
#define FILTERED_VCU_STATUS_VCU_FAULT_MOTOR__PCHG__CONTACTOR__SENSE_CHOICE (2u)
#define FILTERED_VCU_STATUS_VCU_FAULT_MOTOR__PRECHARGE__TIMEOUT_CHOICE (3u)
#define FILTERED_VCU_STATUS_VCU_FAULT_MOTOR__CONTROLLER__FAULT_CHOICE (4u)
#define FILTERED_VCU_STATUS_VCU_FAULT_MOTOR_HV__OVERVOLTAGE_CHOICE (5u)
#define FILTERED_VCU_STATUS_VCU_FAULT_MOTOR_HV__UNDERVOLTAGE_CHOICE (6u)

/* Frame Names. */
#define FILTERED_VCU_STATUS_NAME "VCU_Status"
#define FILTERED_BPS_STATUS_NAME "BPS_Status"
#define FILTERED_DRIVER_INPUT_STATUS_NAME "Driver_Input_Status"
#define FILTERED_BRAKE_PRESSURE_NAME "Brake_Pressure"
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_NAME "Accel_Brake_Position_Voltage"
#define FILTERED_ACCEL_BRAKE_POSITION_NAME "Accel_Brake_Position"

/* Signal Names. */
#define FILTERED_VCU_STATUS_VCU_FAULT_NAME "VCU_Fault"
#define FILTERED_VCU_STATUS_MOTOR_CONTACTOR_STATE_NAME "Motor_Contactor_State"
#define FILTERED_VCU_STATUS_MOTOR_PRECHARGE_CONTACTOR_STATE_NAME "Motor_Precharge_Contactor_State"
#define FILTERED_VCU_STATUS_MOTOR_READY_TO_DRIVE_NAME "Motor_Ready_To_Drive"
#define FILTERED_VCU_STATUS_VCU_DRIVER_INPUT_OK_NAME "VCU_Driver_Input_OK"
#define FILTERED_VCU_STATUS_VCU_PEDALS_OK_NAME "VCU_Pedals_OK"
#define FILTERED_VCU_STATUS_VCU_REGEN_OK_NAME "VCU_Regen_OK"
#define FILTERED_VCU_STATUS_VCU_REGEN_ACTIVE_NAME "VCU_Regen_Active"
#define FILTERED_VCU_STATUS_VCU_FSM_STATE_NAME "VCU_FSM_State"
#define FILTERED_BPS_STATUS_BPS_FAULT_NAME "BPS_Fault"
#define FILTERED_BPS_STATUS_BPS_CHARGE_OK_NAME "BPS_Charge_OK"
#define FILTERED_BPS_STATUS_BPS_REGEN_OK_NAME "BPS_Regen_OK"
#define FILTERED_BPS_STATUS_HV_PLUS_CONTACTOR_STATE_NAME "HV_Plus_Contactor_State"
#define FILTERED_BPS_STATUS_HV_MINUS_CONTACTOR_STATE_NAME "HV_Minus_Contactor_State"
#define FILTERED_BPS_STATUS_ARRAY_CONTACTOR_STATE_NAME "Array_Contactor_State"
#define FILTERED_BPS_STATUS_ARRAY_PRECHARGE_CONTACTOR_STATE_NAME "Array_Precharge_Contactor_State"
#define FILTERED_BPS_STATUS_MAIN_BATTERY_VOLTAGE_NAME "Main_Battery_Voltage"
#define FILTERED_BPS_STATUS_MAIN_BATTERY_AVG_TEMPERATURE_NAME "Main_Battery_Avg_Temperature"
#define FILTERED_DRIVER_INPUT_STATUS_IGNITION_ARRAY_NAME "Ignition_Array"
#define FILTERED_DRIVER_INPUT_STATUS_IGNITION_MOTOR_NAME "Ignition_Motor"
#define FILTERED_DRIVER_INPUT_STATUS_IGNITION_OFF_NAME "Ignition_Off"
#define FILTERED_DRIVER_INPUT_STATUS_CRUISE_ENABLE_NAME "Cruise_Enable"
#define FILTERED_DRIVER_INPUT_STATUS_CRUISE_SET_NAME "Cruise_Set"
#define FILTERED_DRIVER_INPUT_STATUS_GEAR_FORWARD_NAME "Gear_Forward"
#define FILTERED_DRIVER_INPUT_STATUS_GEAR_NEUTRAL_NAME "Gear_Neutral"
#define FILTERED_DRIVER_INPUT_STATUS_GEAR_REVERSE_NAME "Gear_Reverse"
#define FILTERED_DRIVER_INPUT_STATUS_HAZARD_PRESSED_NAME "Hazard_Pressed"
#define FILTERED_DRIVER_INPUT_STATUS_HORN_PRESSED_NAME "Horn_Pressed"
#define FILTERED_DRIVER_INPUT_STATUS_BLINKER_LEFT_NAME "Blinker_Left"
#define FILTERED_DRIVER_INPUT_STATUS_BLINKER_RIGHT_NAME "Blinker_Right"
#define FILTERED_DRIVER_INPUT_STATUS_PUSH_TO_TALK_PRESSED_NAME "PushToTalk_Pressed"
#define FILTERED_DRIVER_INPUT_STATUS_REGEN_ACTIVATE_NAME "Regen_Activate"
#define FILTERED_DRIVER_INPUT_STATUS_REGEN_ENABLE_NAME "Regen_Enable"
#define FILTERED_DRIVER_INPUT_STATUS_STEERING_ANGLE_NAME "Steering_Angle"
#define FILTERED_DRIVER_INPUT_STATUS_STEERING_ANGLE_SPEED_NAME "Steering_Angle_Speed"
#define FILTERED_DRIVER_INPUT_STATUS_STEERING_SENSOR_OK_NAME "Steering_Sensor_OK"
#define FILTERED_DRIVER_INPUT_STATUS_STEERING_SENSOR_CAL_NAME "Steering_Sensor_CAL"
#define FILTERED_DRIVER_INPUT_STATUS_STEERING_SENSOR_TRIM_NAME "Steering_Sensor_TRIM"
#define FILTERED_BRAKE_PRESSURE_BRAKE_PRESSURE_1_NAME "Brake_Pressure_1"
#define FILTERED_BRAKE_PRESSURE_BRAKE_PRESSURE_1_VOLTAGE_NAME "Brake_Pressure_1_Voltage"
#define FILTERED_BRAKE_PRESSURE_BRAKE_PRESSURE_2_NAME "Brake_Pressure_2"
#define FILTERED_BRAKE_PRESSURE_BRAKE_PRESSURE_2_VOLTAGE_NAME "Brake_Pressure_2_Voltage"
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_ACCEL_POS_VOLTAGE_MAIN_NAME "Accel_Pos_Voltage_Main"
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_ACCEL_POS_VOLTAGE_REDUNDANT_NAME "Accel_Pos_Voltage_Redundant"
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_BRAKE_POS_VOLTAGE_MAIN_NAME "Brake_Pos_Voltage_Main"
#define FILTERED_ACCEL_BRAKE_POSITION_VOLTAGE_BRAKE_POS_VOLTAGE_REDUNDANT_NAME "Brake_Pos_Voltage_Redundant"
#define FILTERED_ACCEL_BRAKE_POSITION_ACCEL_POS_MAIN_NAME "Accel_Pos_Main"
#define FILTERED_ACCEL_BRAKE_POSITION_ACCEL_POS_REDUNDANT_NAME "Accel_Pos_Redundant"
#define FILTERED_ACCEL_BRAKE_POSITION_BRAKE_POS_MAIN_NAME "Brake_Pos_Main"
#define FILTERED_ACCEL_BRAKE_POSITION_BRAKE_POS_REDUNDANT_NAME "Brake_Pos_Redundant"
#define FILTERED_ACCEL_BRAKE_POSITION_ACCEL_POS_MAIN_FAULT_NAME "Accel_Pos_Main_Fault"
#define FILTERED_ACCEL_BRAKE_POSITION_ACCEL_POS_REDUNDANT_FAULT_NAME "Accel_Pos_Redundant_Fault"
#define FILTERED_ACCEL_BRAKE_POSITION_BRAKE_POS_MAIN_FAULT_NAME "Brake_Pos_Main_Fault"
#define FILTERED_ACCEL_BRAKE_POSITION_BRAKE_POS_REDUNDANT_FAULT_NAME "Brake_Pos_Redundant_Fault"
#define FILTERED_ACCEL_BRAKE_POSITION_BRAKE_PRESSURE_1_FAULT_NAME "Brake_Pressure_1_Fault"
#define FILTERED_ACCEL_BRAKE_POSITION_BRAKE_PRESSURE_2_FAULT_NAME "Brake_Pressure_2_Fault"

/**
 * Signals in message VCU_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct filtered_vcu_status_t {
    /**
     * VCU Fault State (0 for all clear; see value table for specific faults)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_fault;

    /**
     * Motor Main Contactor State (0 open, 1 closed)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_contactor_state;

    /**
     * Motor Precharge Contactor State (0 open, 1 closed)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_precharge_contactor_state;

    /**
     * VCU has determined the motor controller is ready to receive torque commands
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_ready_to_drive;

    /**
     * VCU is receiving valid data from driver inputs (dash/steering)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_driver_input_ok;

    /**
     * VCU is receiving valid data from accel/brake pedal position sensors
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_pedals_ok;

    /**
     * VCU has determined regenerative braking can be applied
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_regen_ok;

    /**
     * VCU is actively applying regenerative braking
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_regen_active;

    /**
     * VCU finite state machine current state (TODO: value table when states finalized)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_fsm_state;
};

/**
 * Signals in message BPS_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct filtered_bps_status_t {
    /**
     * BPS Fault State (0 for all clear; see value table for specific faults)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bps_fault;

    /**
     * BPS has determined charging the pack is OK (0 not ok, 1 ok)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bps_charge_ok;

    /**
     * BPS has determined regenerative braking is OK (0 not ok, 1 ok)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bps_regen_ok;

    /**
     * HV+ Contactor State (0 open, 1 closed)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t hv_plus_contactor_state;

    /**
     * HV- Contactor State (0 open, 1 closed)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t hv_minus_contactor_state;

    /**
     * Array Main Contactor State (0 open, 1 closed)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t array_contactor_state;

    /**
     * Array Precharge Contactor State (0 open, 1 closed)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t array_precharge_contactor_state;

    /**
     * Total battery pack voltage as determined by the BPS
     *
     * Range: 0..16777215 (0..16777.215 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint32_t main_battery_voltage;

    /**
     * Average pack temperature as determined by the BPS
     *
     * Range: -32768..32767 (-327.68..327.67 -)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t main_battery_avg_temperature;
};

/**
 * Signals in message Driver_Input_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct filtered_driver_input_status_t {
    /**
     * Ignition Switch in Array Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t ignition_array;

    /**
     * Ignition Switch in Motor Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t ignition_motor;

    /**
     * Ignition Switch in Off Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t ignition_off;

    /**
     * Cruise Enable Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cruise_enable;

    /**
     * Cruise Set Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cruise_set;

    /**
     * Gear Switch in Forward Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t gear_forward;

    /**
     * Gear Switch in Neutral Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t gear_neutral;

    /**
     * Gear Switch in Reverse Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t gear_reverse;

    /**
     * Hazard Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t hazard_pressed;

    /**
     * Horn Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t horn_pressed;

    /**
     * Blinker Switch in Left Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t blinker_left;

    /**
     * Blinker Switch in Right Position
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t blinker_right;

    /**
     * Push To Talk (PTT) Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t push_to_talk_pressed;

    /**
     * Regen Activate Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t regen_activate;

    /**
     * Regen Enable Button Pressed
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t regen_enable;

    /**
     * Measured steering wheel angle
     *
     * Range: -32768..32767 (-3276.8..3276.7 Degrees)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t steering_angle;

    /**
     * Measured steering wheel angular speed
     *
     * Range: 0..255 (0..1020 Degrees/s)
     * Scale: 4
     * Offset: 0
     */
    uint8_t steering_angle_speed;

    /**
     * Sensor validity bit
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t steering_sensor_ok;

    /**
     * Sensor calibration status bit
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t steering_sensor_cal;

    /**
     * Sensor trimmed bit
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t steering_sensor_trim;
};

/**
 * Signals in message Brake_Pressure.
 *
 * All signal values are as on the CAN bus.
 */
struct filtered_brake_pressure_t {
    /**
     * Brake Pressure PSI (Sensor 1)
     *
     * Range: 0..30000 (0..3000 PSI)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t brake_pressure_1;

    /**
     * Brake Pressure Raw Voltage (Sensor 1)
     *
     * Range: 0..3300 (0..3.3 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t brake_pressure_1_voltage;

    /**
     * Brake Pressure PSI (Sensor 2)
     *
     * Range: 0..30000 (0..3000 PSI)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t brake_pressure_2;

    /**
     * Brake Pressure Raw Voltage (Sensor 2)
     *
     * Range: 0..3300 (0..3.3 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t brake_pressure_2_voltage;
};

/**
 * Signals in message Accel_Brake_Position_Voltage.
 *
 * All signal values are as on the CAN bus.
 */
struct filtered_accel_brake_position_voltage_t {
    /**
     * Accelerator Pedal Raw Voltage Measurement (Main Sensor)
     *
     * Range: 0..3300 (0..3.3 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t accel_pos_voltage_main;

    /**
     * Accelerator Pedal Raw Voltage Measurement (Redundant Sensor)
     *
     * Range: 0..3300 (0..3.3 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t accel_pos_voltage_redundant;

    /**
     * Brake Pedal Raw Voltage Measurement (Main Sensor)
     *
     * Range: 0..3300 (0..3.3 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t brake_pos_voltage_main;

    /**
     * Brake Pedal Raw Voltage Measurement (Redundant Sensor)
     *
     * Range: 0..3300 (0..3.3 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t brake_pos_voltage_redundant;
};

/**
 * Signals in message Accel_Brake_Position.
 *
 * All signal values are as on the CAN bus.
 */
struct filtered_accel_brake_position_t {
    /**
     * Accelerator Pedal Position (Main Sensor)
     *
     * Range: 0..100 (0..100 Percent)
     * Scale: 1
     * Offset: 0
     */
    uint8_t accel_pos_main;

    /**
     * Accelerator Pedal Position (Redundant Sensor)
     *
     * Range: 0..100 (0..100 Percent)
     * Scale: 1
     * Offset: 0
     */
    uint8_t accel_pos_redundant;

    /**
     * Brake Pedal Position (Main Sensor)
     *
     * Range: 0..100 (0..100 Percent)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pos_main;

    /**
     * Brake Pedal Position (Redundant Sensor)
     *
     * Range: 0..100 (0..100 Percent)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pos_redundant;

    /**
     * Accelerator Pedal Main Sensor Fault (0 normal, 1 fault)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t accel_pos_main_fault;

    /**
     * Accelerator Pedal Redundant Sensor Fault (0 normal, 1 fault)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t accel_pos_redundant_fault;

    /**
     * Brake Pedal Main Sensor Fault (0 normal, 1 fault)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pos_main_fault;

    /**
     * Brake Pedal Redundant Sensor Fault (0 normal, 1 fault)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pos_redundant_fault;

    /**
     * Brake Pressure Sensor 1 Fault (0 normal, 1 fault)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pressure_1_fault;

    /**
     * Brake Pressure Sensor 2 Fault (0 normal, 1 fault)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pressure_2_fault;
};

/**
 * Pack message VCU_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int filtered_vcu_status_pack(
    uint8_t *dst_p,
    const struct filtered_vcu_status_t *src_p,
    size_t size);

/**
 * Unpack message VCU_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int filtered_vcu_status_unpack(
    struct filtered_vcu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VCU_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int filtered_vcu_status_init(struct filtered_vcu_status_t *msg_p);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_vcu_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_motor_contactor_state_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_motor_precharge_contactor_state_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_motor_ready_to_drive_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_vcu_driver_input_ok_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_vcu_pedals_ok_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_vcu_regen_ok_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_vcu_regen_active_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_vcu_status_vcu_fsm_state_is_in_range(uint8_t value);

/**
 * Pack message BPS_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int filtered_bps_status_pack(
    uint8_t *dst_p,
    const struct filtered_bps_status_t *src_p,
    size_t size);

/**
 * Unpack message BPS_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int filtered_bps_status_unpack(
    struct filtered_bps_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BPS_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int filtered_bps_status_init(struct filtered_bps_status_t *msg_p);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_bps_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_bps_charge_ok_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_bps_regen_ok_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_hv_plus_contactor_state_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_hv_minus_contactor_state_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_array_contactor_state_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_array_precharge_contactor_state_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_main_battery_voltage_is_in_range(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_bps_status_main_battery_avg_temperature_is_in_range(int16_t value);

/**
 * Pack message Driver_Input_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int filtered_driver_input_status_pack(
    uint8_t *dst_p,
    const struct filtered_driver_input_status_t *src_p,
    size_t size);

/**
 * Unpack message Driver_Input_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int filtered_driver_input_status_unpack(
    struct filtered_driver_input_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Driver_Input_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int filtered_driver_input_status_init(struct filtered_driver_input_status_t *msg_p);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_ignition_array_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_ignition_motor_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_ignition_off_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_cruise_enable_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_cruise_set_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_gear_forward_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_gear_neutral_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_gear_reverse_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_hazard_pressed_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_horn_pressed_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_blinker_left_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_blinker_right_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_push_to_talk_pressed_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_regen_activate_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_regen_enable_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_steering_angle_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_steering_angle_speed_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_steering_sensor_ok_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_steering_sensor_cal_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_driver_input_status_steering_sensor_trim_is_in_range(uint8_t value);

/**
 * Pack message Brake_Pressure.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int filtered_brake_pressure_pack(
    uint8_t *dst_p,
    const struct filtered_brake_pressure_t *src_p,
    size_t size);

/**
 * Unpack message Brake_Pressure.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int filtered_brake_pressure_unpack(
    struct filtered_brake_pressure_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Brake_Pressure.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int filtered_brake_pressure_init(struct filtered_brake_pressure_t *msg_p);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_brake_pressure_brake_pressure_1_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_brake_pressure_brake_pressure_1_voltage_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_brake_pressure_brake_pressure_2_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_brake_pressure_brake_pressure_2_voltage_is_in_range(uint16_t value);

/**
 * Pack message Accel_Brake_Position_Voltage.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int filtered_accel_brake_position_voltage_pack(
    uint8_t *dst_p,
    const struct filtered_accel_brake_position_voltage_t *src_p,
    size_t size);

/**
 * Unpack message Accel_Brake_Position_Voltage.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int filtered_accel_brake_position_voltage_unpack(
    struct filtered_accel_brake_position_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Accel_Brake_Position_Voltage.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int filtered_accel_brake_position_voltage_init(struct filtered_accel_brake_position_voltage_t *msg_p);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_voltage_accel_pos_voltage_main_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_voltage_accel_pos_voltage_redundant_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_voltage_brake_pos_voltage_main_is_in_range(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_voltage_brake_pos_voltage_redundant_is_in_range(uint16_t value);

/**
 * Pack message Accel_Brake_Position.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int filtered_accel_brake_position_pack(
    uint8_t *dst_p,
    const struct filtered_accel_brake_position_t *src_p,
    size_t size);

/**
 * Unpack message Accel_Brake_Position.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int filtered_accel_brake_position_unpack(
    struct filtered_accel_brake_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Accel_Brake_Position.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int filtered_accel_brake_position_init(struct filtered_accel_brake_position_t *msg_p);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_accel_pos_main_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_accel_pos_redundant_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_brake_pos_main_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_brake_pos_redundant_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_accel_pos_main_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_accel_pos_redundant_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_brake_pos_main_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_brake_pos_redundant_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_brake_pressure_1_fault_is_in_range(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool filtered_accel_brake_position_brake_pressure_2_fault_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
