// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

CAN_RECV_ENTRY(0x321, 8, true)  // 801 - test
CAN_RECV_ENTRY(0x001, 8, true)  // BPS_STATUS
CAN_RECV_ENTRY(0x650, 8, true)  // BRAKE_PRESSURE
CAN_RECV_ENTRY(0x600, 8, true)  // LV_CARRIER_STATUS
CAN_RECV_ENTRY(0x2B0, 8, true)  // LWS_STANDARD
CAN_RECV_ENTRY(0x060, 8, true)  // DRIVER_INPUT_STATUS
CAN_RECV_ENTRY(0x050, 8, true)  // ACCEL_BRAKE_POSITION
CAN_RECV_ENTRY(0x021, 8, true)  // PRECHARGE_VOLTAGES
CAN_RECV_ENTRY(0x015, 8, true)  // CONTROLS_STATUS
