#include "CarCAN_can_msgs.h"
// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

CAN_RECV_ENTRY(0x001, 5, false)
CAN_RECV_ENTRY(0x002, 8, false)
CAN_RECV_ENTRY(0x003, 3, false)
CAN_RECV_ENTRY(CAN_ID_VCU_STATUS, 6, true)
CAN_RECV_ENTRY(CAN_ID_DRIVER_INPUT_STATUS, 2, true)
CAN_RECV_ENTRY(CAN_ID_VCU_PRECHARGE_VOLTAGES, 6, true)
CAN_RECV_ENTRY(0x321, 8, false)