#ifndef PINDEFS_H
#define PINDEFS_H

#include "stm32xx_hal.h"

#define HB_LED_PORT GPIOC
#define HB_LED_PIN GPIO_PIN_3

#define ADC_PORT GPIOB
#define MOTOR_ADC_CHANNEL 11 // ADC channel for motor voltage sensing
#define BATTERY_ADC_CHANNEL 12 // ADC channel for battery voltage sensing

#define CAR_STATE_DRIVABLE_PORT GPIOC
#define CAR_STATE_DRIVABLE_PIN GPIO_PIN_6

#define CAR_STATE_DRIVING_PORT GPIOC
#define CAR_STATE_DRIVING_PIN GPIO_PIN_9

#define CAR_STATE_CRUISE_PORT GPIOB
#define CAR_STATE_CRUISE_PIN GPIO_PIN_13

#define CAR_STATE_REGEN_PORT GPIOB
#define CAR_STATE_REGEN_PIN GPIO_PIN_15

#define CAR_STATE_BPSFAULT_PORT GPIOB
#define CAR_STATE_BPSFAULT_PIN GPIO_PIN_9

#define CAR_STATE_HB_PORT GPIOB
#define CAR_STATE_HB_PIN GPIO_PIN_14 //

#define MOTOR_CONTACTOR_M_SENSE_TO_PORT GPIOC
#define MOTOR_CONTACTOR_M_SENSE_TO_PIN GPIO_PIN_7

#define MOTOR_CONTACTOR_ENABLE_PORT GPIOC
#define MOTOR_CONTACTOR_ENABLE_PIN GPIO_PIN_0

#define MOTOR_CONTACTOR_SENSE_PORT GPIOC
#define MOTOR_CONTACTOR_SENSE_PIN GPIO_PIN_2

#define PRECHARGE_PRE_COMPLETE_PORT GPIOC
#define PRECHARGE_PRE_COMPLETE_PIN GPIO_PIN_8

#define PRECHARGE_PRECHARGE_TO_PORT GPIOD
#define PRECHARGE_PRECHARGE_TO_PIN GPIO_PIN_2

#define PRECHARGE_PRE_SENSE_TO_PORT GPIOC
#define PRECHARGE_PRE_SENSE_TO_PIN GPIO_PIN_12

#define PRECHARGE_PRE_ENABLE_PORT GPIOC
#define PRECHARGE_PRE_ENABLE_PIN GPIO_PIN_5

#define PRECHARGE_PRE_SENSE_PORT GPIOC
#define PRECHARGE_PRE_SENSE_PIN GPIO_PIN_4 //

#define MOTOR_FAULT_HALL_PORT GPIOB
#define MOTOR_FAULT_HALL_PIN GPIO_PIN_3

#define MOTOR_FAULT_DAWG_PORT GPIOB
#define MOTOR_FAULT_DAWG_PIN GPIO_PIN_5

#define MOTOR_FAULT_SWOC_PORT GPIOA
#define MOTOR_FAULT_SWOC_PIN GPIO_PIN_10

#define MOTOR_FAULT_FAULT_PORT GPIOB
#define MOTOR_FAULT_FAULT_PIN GPIO_PIN_4

/**
 * @brief object that holds pin num and port of a GPIO pin
 */
typedef struct {
    GPIO_TypeDef* port; // e.g., GPIOA
    uint16_t      pin;  // e.g., GPIO_PIN_3
} GpioPin_t;

#endif