#include "stm32xx_hal.h"

#define HB_LED_PORT GPIOB
#define HB_LED_PIN GPIO_PIN_14

#define ADCPORT GPIOB
#define ADC1 GPIO_PIN_12
#define ADC2 GPIO_PIN_2

#define PRECHARGESTATUSLEDPORT GPIOC
#define PRECHARGETIMEOUTLED GPIO_PIN_12
#define PRECHARGECOMPLETELED GPIO_PIN_8