#include "stm32xx_hal.h"

#define HB_LED_PORT GPIOB
#define HB_LED_PIN GPIO_PIN_14

#define ADC_PORT GPIOB
#define ADC1 GPIO_PIN_12
#define ADC2 GPIO_PIN_2

#define PRECHARGE_STATUS_LED_PORT GPIOC
#define PRECHARGE_TIMEOUT_LED GPIO_PIN_12
#define PRECHARGE_COMPLETELED GPIO_PIN_8