//Only need the size to be 1 for latest, but may want to increase this for logging purposes
//Makefile needs to point to this for FSM entries

#define CAN_ID_VCU_STATUS 0x10
#define CAN_ID_CONTROLS_STATUS 0x15
#define CAN_ID_VCU_PRECHARGE_VOLTAGES 0x21
#define CAN_ID_ACCEL_BRAKE_POSITION 0x50
#define CAN_ID_ACCEL_BRAKE_POSITION_VOLTAGE 0x51
#define CAN_ID_DRIVER_INPUT_STATUS 0x60
#define CAN_ID_MPPT_A_POWER 0x200
#define CAN_ID_MPPT_A_STATUS 0x201
#define CAN_ID_MPPT_A_SETMODE 0x209
#define CAN_ID_MPPT_B_POWER 0x210
#define CAN_ID_MPPT_B_STATUS 0x211
#define CAN_ID_MPPT_B_SETMODE 0x219
#define CAN_ID_MPPT_C_POWER 0x220
#define CAN_ID_MPPT_C_STATUS 0x221
#define CAN_ID_MPPT_C_SETMODE 0x229
#define CAN_ID_LWS_STANDARD 0x2B0
#define CAN_ID_SUPP_BATTERY_STATUS 0x300
#define CAN_ID_SUPP_BATTERY_CHARGER_STATUS 0x301
#define CAN_ID_BBPDU_STATUS 0x350
#define CAN_ID_BBPDU_SET_SWITCHES 0x351
#define CAN_ID_BBPDU_SET_CURRENT_LIMIT 0x352
#define CAN_ID_PUMP_STATUS_FLOWRATE 0x500
#define CAN_ID_COOLANT_TEMPERATURE 0x501
#define CAN_ID_RADIATOR_FANSPEED 0x502
#define CAN_ID_LV_CARRIER_STATUS 0x600
#define CAN_ID_BRAKE_PRESSURE 0x650
#define CAN_ID_LIGHTING_BOARD0_STATUS 0x670
#define CAN_ID_LIGHTING_BOARD1_STATUS 0x671
#define CAN_ID_LIGHTING_BOARD2_STATUS 0x672
#define CAN_ID_LIGHTING_BOARD3_STATUS 0x673
#define CAN_ID_LIGHTING_BOARD4_STATUS 0x674
#define CAN_ID_LIGHTING_BOARD5_STATUS 0x675
#define CAN_ID_LIGHTING_BOARD6_STATUS 0x676
#define CAN_ID_DISPLAY_CAMERAS_STATUS 0x700
#define CAN_ID_TELEMETRY_STATUS 0x750
#define CAN_ID_LWS_CONFIG 0x7C0


//CAR CAN

CAN_RECV_ENTRY(CAN_ID_VCU_STATUS,                    1, true)
CAN_RECV_ENTRY(CAN_ID_CONTROLS_STATUS,               1, true)
CAN_RECV_ENTRY(CAN_ID_VCU_PRECHARGE_VOLTAGES,        1, true)
CAN_RECV_ENTRY(CAN_ID_ACCEL_BRAKE_POSITION,          1, true)
CAN_RECV_ENTRY(CAN_ID_ACCEL_BRAKE_POSITION_VOLTAGE,  1, true)
CAN_RECV_ENTRY(CAN_ID_DRIVER_INPUT_STATUS,           1, true)
CAN_RECV_ENTRY(CAN_ID_LWS_STANDARD,                  1, true)
CAN_RECV_ENTRY(CAN_ID_LV_CARRIER_STATUS,             1, true)
CAN_RECV_ENTRY(CAN_ID_BRAKE_PRESSURE,                1, true)
CAN_RECV_ENTRY(CAN_ID_LWS_CONFIG,                    1, true)
