// Do not delete this file; it is used for FDCAN3
// but since we can't undefine it this must exist

//Only need the size to be 1 for latest, but may want to increase this for logging purposes
//Makefile needs to point to this for FSM entries

#define CAN_ID_MC_DRIVECOMMAND 0x401
#define CAN_ID_MC_POWERCOMMAND 0x402
#define CAN_ID_MC_RESETCOMMAND 0x403
#define CAN_ID_MC_INFO 0x420
#define CAN_ID_MC_STATUS 0x421
#define CAN_ID_MC_BUSMEASUREMENT 0x422
#define CAN_ID_MC_VELOCITYMEASUREMENT 0x423
#define CAN_ID_MC_PHASECURRENTMEASUREMENT 0x424
#define CAN_ID_MC_MOTORVOLTAGEVECTORMEASUREMENT 0x425
#define CAN_ID_MC_MOTORCURRENTVECTORMEASUREMENT 0x426
#define CAN_ID_MC_BACKEMFMEASUREMENTPREDICTION 0x427
#define CAN_ID_MC_15VRAILMEASUREMENT 0x428
#define CAN_ID_MC_3V319VRAILMEASUREMENT 0x429
#define CAN_ID_MC_MOTOR_TEMPMEASUREMENT 0x42B
#define CAN_ID_MC_DSPBOARDTEMPMEASUREMENT 0x42C
#define CAN_ID_MC_ODOMETERBUSAHMEASUREMENT 0x42E
#define CAN_ID_MC_SLIPSPEEDMEASUREMENT 0x437

//Motor CAN Receive
CAN_RECV_ENTRY(CAN_ID_MC_DRIVECOMMAND,                  1, true)
CAN_RECV_ENTRY(CAN_ID_MC_POWERCOMMAND,                  1, true)
CAN_RECV_ENTRY(CAN_ID_MC_RESETCOMMAND,                  1, true)
CAN_RECV_ENTRY(CAN_ID_MC_INFO,                          1, true)
CAN_RECV_ENTRY(CAN_ID_MC_STATUS,                        1, true)
CAN_RECV_ENTRY(CAN_ID_MC_BUSMEASUREMENT,                1, true)
CAN_RECV_ENTRY(CAN_ID_MC_VELOCITYMEASUREMENT,           1, true)
CAN_RECV_ENTRY(CAN_ID_MC_PHASECURRENTMEASUREMENT,       1, true)
CAN_RECV_ENTRY(CAN_ID_MC_MOTORVOLTAGEVECTORMEASUREMENT, 1, true)
CAN_RECV_ENTRY(CAN_ID_MC_MOTORCURRENTVECTORMEASUREMENT, 1, true)
CAN_RECV_ENTRY(CAN_ID_MC_BACKEMFMEASUREMENTPREDICTION,  1, true)
CAN_RECV_ENTRY(CAN_ID_MC_15VRAILMEASUREMENT,            1, true)
CAN_RECV_ENTRY(CAN_ID_MC_3V319VRAILMEASUREMENT,         1, true)
CAN_RECV_ENTRY(CAN_ID_MC_MOTOR_TEMPMEASUREMENT,         1, true)
CAN_RECV_ENTRY(CAN_ID_MC_DSPBOARDTEMPMEASUREMENT,       1, true)
CAN_RECV_ENTRY(CAN_ID_MC_ODOMETERBUSAHMEASUREMENT,      1, true)
CAN_RECV_ENTRY(CAN_ID_MC_SLIPSPEEDMEASUREMENT,          1, true)