/**
 * @file fsm_table.h
 * @brief Auto-generated FSM next-state table
 *        DO NOT EDIT — regenerate with generate_fsm.py
 */

#pragma once
#include "fsm.h"

// Instantiated in exactly one .c file via:
//   #define DEFINE_FSM_TABLE
//   #include "fsm_table.h"

extern TritiumState_t FSM[NUM_STATES];

#ifdef DEFINE_FSM_TABLE
TritiumState_t FSM[NUM_STATES] = {

    [STATE_INIT] = { STATE_INIT, NULL, {
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY
    }},

    [FORWARD_DRIVE] = { FORWARD_DRIVE, NULL, {
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            CRUISE_CONTROL, NEUTRAL, CRUISE_CONTROL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            CRUISE_CONTROL, NEUTRAL, CRUISE_CONTROL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            FORWARD_DRIVE, NEUTRAL, FORWARD_DRIVE, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            CRUISE_CONTROL, NEUTRAL, CRUISE_CONTROL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            REGEN, NEUTRAL, REGEN, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL,
            REGEN, NEUTRAL, REGEN, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL
    }},

    [NEUTRAL] = { NEUTRAL, NULL, {
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE,
            NEUTRAL, NEUTRAL, FORWARD_DRIVE, FORWARD_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE, REVERSE_DRIVE
    }},

    [REVERSE_DRIVE] = { REVERSE_DRIVE, NULL, {
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL,
            NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, REVERSE_DRIVE, REVERSE_DRIVE, NEUTRAL, NEUTRAL
    }},

    [REGEN] = { REGEN, NULL, {
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            FORWARD_DRIVE, FORWARD_DRIVE, REGEN, REGEN, FORWARD_DRIVE, FORWARD_DRIVE, REGEN, REGEN,
            FORWARD_DRIVE, FORWARD_DRIVE, REGEN, REGEN, FORWARD_DRIVE, FORWARD_DRIVE, REGEN, REGEN
    }},

    [CRUISE_CONTROL] = { CRUISE_CONTROL, NULL, {
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL,
            FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE, FORWARD_DRIVE,
            CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL, CRUISE_CONTROL
    }},

    [DISABLED] = { DISABLED, NULL, {
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED,
            DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED, DISABLED
    }},

    [CAR_NOT_READY] = { CAR_NOT_READY, NULL, {
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY,
            CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY, CAR_NOT_READY
    }},

};
#endif // DEFINE_FSM_TABLE
