/* ======================================================
   AUTO-GENERATED FILE - DO NOT EDIT
   Classic CAN enforced (<=8 bytes)
   ====================================================== */

/**
 * @file filtered.c
 *
 * @brief This source file was generated by cantools version 41.1.1 Thu Feb 26 04:09:10 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "filtered.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int filtered_vcu_status_pack(
    uint8_t *dst_p,
    const struct filtered_vcu_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->vcu_fault, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->motor_contactor_state, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->motor_precharge_contactor_state, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->motor_ready_to_drive, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->vcu_driver_input_ok, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->vcu_pedals_ok, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->vcu_regen_ok, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->vcu_regen_active, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->vcu_fsm_state, 0u, 0x0fu);

    return (3);
}

int filtered_vcu_status_unpack(
    struct filtered_vcu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->vcu_fault = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->motor_contactor_state = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->motor_precharge_contactor_state = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->motor_ready_to_drive = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->vcu_driver_input_ok = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->vcu_pedals_ok = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->vcu_regen_ok = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->vcu_regen_active = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->vcu_fsm_state = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);

    return (0);
}

int filtered_vcu_status_init(struct filtered_vcu_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct filtered_vcu_status_t));

    return 0;
}

bool filtered_vcu_status_vcu_fault_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool filtered_vcu_status_motor_contactor_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_motor_precharge_contactor_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_motor_ready_to_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_vcu_driver_input_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_vcu_pedals_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_vcu_regen_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_vcu_regen_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_vcu_status_vcu_fsm_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int filtered_bps_status_pack(
    uint8_t *dst_p,
    const struct filtered_bps_status_t *src_p,
    size_t size)
{
    uint16_t main_battery_avg_temperature;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->bps_fault, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bps_charge_ok, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->bps_regen_ok, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->hv_plus_contactor_state, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->hv_minus_contactor_state, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->array_contactor_state, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->array_precharge_contactor_state, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u32(src_p->main_battery_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->main_battery_voltage, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->main_battery_voltage, 16u, 0xffu);
    main_battery_avg_temperature = (uint16_t)src_p->main_battery_avg_temperature;
    dst_p[5] |= pack_left_shift_u16(main_battery_avg_temperature, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(main_battery_avg_temperature, 8u, 0xffu);

    return (7);
}

int filtered_bps_status_unpack(
    struct filtered_bps_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t main_battery_avg_temperature;

    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->bps_fault = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bps_charge_ok = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->bps_regen_ok = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->hv_plus_contactor_state = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->hv_minus_contactor_state = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->array_contactor_state = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->array_precharge_contactor_state = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->main_battery_voltage = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->main_battery_voltage |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->main_battery_voltage |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    main_battery_avg_temperature = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    main_battery_avg_temperature |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->main_battery_avg_temperature = (int16_t)main_battery_avg_temperature;

    return (0);
}

int filtered_bps_status_init(struct filtered_bps_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct filtered_bps_status_t));

    return 0;
}

bool filtered_bps_status_bps_fault_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool filtered_bps_status_bps_charge_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_bps_status_bps_regen_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_bps_status_hv_plus_contactor_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_bps_status_hv_minus_contactor_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_bps_status_array_contactor_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_bps_status_array_precharge_contactor_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_bps_status_main_battery_voltage_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool filtered_bps_status_main_battery_avg_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int filtered_driver_input_status_pack(
    uint8_t *dst_p,
    const struct filtered_driver_input_status_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->ignition_array, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ignition_motor, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->ignition_off, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->cruise_enable, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->cruise_set, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->gear_forward, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->gear_neutral, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->gear_reverse, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->hazard_pressed, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->horn_pressed, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->blinker_left, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->blinker_right, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->push_to_talk_pressed, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->regen_activate, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->regen_enable, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u16(src_p->steering_angle, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->steering_angle, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->steering_angle_speed, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->steering_sensor_ok, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->steering_sensor_cal, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->steering_sensor_trim, 2u, 0x04u);

    return (6);
}

int filtered_driver_input_status_unpack(
    struct filtered_driver_input_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->ignition_array = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ignition_motor = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->ignition_off = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->cruise_enable = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->cruise_set = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->gear_forward = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->gear_neutral = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->gear_reverse = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->hazard_pressed = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->horn_pressed = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->blinker_left = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->blinker_right = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->push_to_talk_pressed = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->regen_activate = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->regen_enable = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->steering_angle = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->steering_angle |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->steering_angle_speed = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->steering_sensor_ok = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->steering_sensor_cal = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->steering_sensor_trim = unpack_right_shift_u8(src_p[5], 2u, 0x04u);

    return (0);
}

int filtered_driver_input_status_init(struct filtered_driver_input_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct filtered_driver_input_status_t));

    return 0;
}

bool filtered_driver_input_status_ignition_array_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_ignition_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_ignition_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_cruise_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_cruise_set_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_gear_forward_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_gear_neutral_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_gear_reverse_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_hazard_pressed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_horn_pressed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_blinker_left_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_blinker_right_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_push_to_talk_pressed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_regen_activate_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_regen_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_steering_angle_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool filtered_driver_input_status_steering_angle_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool filtered_driver_input_status_steering_sensor_ok_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_steering_sensor_cal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_driver_input_status_steering_sensor_trim_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int filtered_brake_pressure_pack(
    uint8_t *dst_p,
    const struct filtered_brake_pressure_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->brake_pressure_1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->brake_pressure_1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->brake_pressure_1_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->brake_pressure_1_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->brake_pressure_2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->brake_pressure_2, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->brake_pressure_2_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->brake_pressure_2_voltage, 8u, 0xffu);

    return (8);
}

int filtered_brake_pressure_unpack(
    struct filtered_brake_pressure_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->brake_pressure_1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->brake_pressure_1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->brake_pressure_1_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->brake_pressure_1_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->brake_pressure_2 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->brake_pressure_2 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->brake_pressure_2_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->brake_pressure_2_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int filtered_brake_pressure_init(struct filtered_brake_pressure_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct filtered_brake_pressure_t));

    return 0;
}

bool filtered_brake_pressure_brake_pressure_1_is_in_range(uint16_t value)
{
    return (value <= 30000u);
}

bool filtered_brake_pressure_brake_pressure_1_voltage_is_in_range(uint16_t value)
{
    return (value <= 3300u);
}

bool filtered_brake_pressure_brake_pressure_2_is_in_range(uint16_t value)
{
    return (value <= 30000u);
}

bool filtered_brake_pressure_brake_pressure_2_voltage_is_in_range(uint16_t value)
{
    return (value <= 3300u);
}

int filtered_accel_brake_position_voltage_pack(
    uint8_t *dst_p,
    const struct filtered_accel_brake_position_voltage_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->accel_pos_voltage_main, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->accel_pos_voltage_main, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->accel_pos_voltage_redundant, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->accel_pos_voltage_redundant, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->brake_pos_voltage_main, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->brake_pos_voltage_main, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->brake_pos_voltage_redundant, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->brake_pos_voltage_redundant, 8u, 0xffu);

    return (8);
}

int filtered_accel_brake_position_voltage_unpack(
    struct filtered_accel_brake_position_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->accel_pos_voltage_main = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->accel_pos_voltage_main |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_pos_voltage_redundant = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->accel_pos_voltage_redundant |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->brake_pos_voltage_main = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->brake_pos_voltage_main |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->brake_pos_voltage_redundant = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->brake_pos_voltage_redundant |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int filtered_accel_brake_position_voltage_init(struct filtered_accel_brake_position_voltage_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct filtered_accel_brake_position_voltage_t));

    return 0;
}

bool filtered_accel_brake_position_voltage_accel_pos_voltage_main_is_in_range(uint16_t value)
{
    return (value <= 3300u);
}

bool filtered_accel_brake_position_voltage_accel_pos_voltage_redundant_is_in_range(uint16_t value)
{
    return (value <= 3300u);
}

bool filtered_accel_brake_position_voltage_brake_pos_voltage_main_is_in_range(uint16_t value)
{
    return (value <= 3300u);
}

bool filtered_accel_brake_position_voltage_brake_pos_voltage_redundant_is_in_range(uint16_t value)
{
    return (value <= 3300u);
}

int filtered_accel_brake_position_pack(
    uint8_t *dst_p,
    const struct filtered_accel_brake_position_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->accel_pos_main, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->accel_pos_redundant, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_pos_main, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_pos_redundant, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->accel_pos_main_fault, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->accel_pos_redundant_fault, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->brake_pos_main_fault, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->brake_pos_redundant_fault, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->brake_pressure_1_fault, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->brake_pressure_2_fault, 5u, 0x20u);

    return (5);
}

int filtered_accel_brake_position_unpack(
    struct filtered_accel_brake_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->accel_pos_main = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->accel_pos_redundant = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_pos_main = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->brake_pos_redundant = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->accel_pos_main_fault = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->accel_pos_redundant_fault = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->brake_pos_main_fault = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->brake_pos_redundant_fault = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->brake_pressure_1_fault = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->brake_pressure_2_fault = unpack_right_shift_u8(src_p[4], 5u, 0x20u);

    return (0);
}

int filtered_accel_brake_position_init(struct filtered_accel_brake_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct filtered_accel_brake_position_t));

    return 0;
}

bool filtered_accel_brake_position_accel_pos_main_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool filtered_accel_brake_position_accel_pos_redundant_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool filtered_accel_brake_position_brake_pos_main_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool filtered_accel_brake_position_brake_pos_redundant_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool filtered_accel_brake_position_accel_pos_main_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_accel_brake_position_accel_pos_redundant_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_accel_brake_position_brake_pos_main_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_accel_brake_position_brake_pos_redundant_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_accel_brake_position_brake_pressure_1_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool filtered_accel_brake_position_brake_pressure_2_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
